# This is the full content for your NEW configuration file.
# It's a "rulebook" that defines the changelog categories.

changelog:
  exclude:
    # Exclude bots from the contributor list
    authors:
      - "github-actions[bot]"
      - "dependabot[bot]"
  categories:
    - title: "🚀 New Features"
      # Commits starting with "feat:" or "feature:" will go here
      prefixes:
        - "feat"
        - "feature"
    - title: "🐛 Bug Fixes"
      # Commits starting with "fix:" or "bugfix:" will go here
      prefixes:
        - "fix"
        - "bugfix"
    - title: "🛠️ Maintenance & Refactoring"
      # Commits for chores, CI/CD, refactoring, etc.
      prefixes:
        - "chore"
        - "refactor"
        - "ci"
        - "build"
    - title: "📖 Documentation"
      prefixes:
        - "docs"
    - title: "🏎️ Performance"
      prefixes:
        - "perf"
    # This is a catch-all for any other commits that don't match a prefix
    - title: "Other Changes"
      # An empty prefix list acts as a default
      prefixes: []
