# .github/workflows/pull-request-check.yml
# This workflow runs automatically on every Pull Request to the 'main' branch

name: Pull Request Check

on:
  pull_request:
    branches: [ main ] # This triggers the workflow on PRs targeting 'main'

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # Caching dependencies is very useful here, as this workflow runs often.
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt || echo "No requirements.txt found"
      shell: bash

    - name: Build with PyInstaller
      run: pyinstaller --noconsole --onefile main.py
      shell: bash

    - name: Run Executable in Test Mode
      run: |
        echo "--- Running main.exe with --test argument ---"
        ./dist/main.exe --test
        echo "--- Execution Finished ---"
      shell: bash
