name: Build and Release EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get commit message
      id: commit
      run: |
        msg=$(git log -1 --pretty=%B)
        echo "message=$msg" >> $GITHUB_OUTPUT

    - name: Validate commit message and extract build number
      id: validate
      run: |
        echo "Commit message: '${{ steps.commit.outputs.message }}'"
        if [[ "${{ steps.commit.outputs.message }}" =~ ^Build[[:space:]]+([0-9]+)$ ]]; then
          echo "match=true" >> $GITHUB_OUTPUT
          echo "build_number=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
        else
          echo "match=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Stop if not a release commit
      if: steps.validate.outputs.match != 'true'
      run: echo "Not a 'Build <number>' commit — skipping release." && exit 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt || true

    - name: Build with PyInstaller
      run: pyinstaller --noconsole --onefile main.py

    - name: Generate release notes from commits
      id: notes
      run: |
        git fetch --tags
        latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        echo "latest_tag=$latest_tag"
        if [ -n "$latest_tag" ]; then
          git log "$latest_tag"..HEAD --pretty=format:"- %h %s by @%an" > release_notes.md
        else
          git log --pretty=format:"- %h %s by @%an" > release_notes.md
        fi
        echo "release_body<<EOF" >> $GITHUB_OUTPUT
        echo "Changes in Build ${{ steps.validate.outputs.build_number }}:" >> $GITHUB_OUTPUT
        cat release_notes.md >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      shell: bash

    - name: Upload EXE to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: Build ${{ steps.validate.outputs.build_number }}
        tag_name: build-${{ steps.validate.outputs.build_number }}
        body: ${{ steps.notes.outputs.release_body }}
        files: dist/main.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
